### ISSUE TITLE
[BUG] Converting timestamp

### ISSUE THREAD

**Issue by fis60** [jsonzilla/vtt-to-srt.py#26]
**Note: for support questions, please use stackoverflow**.
This repository's issues are reserved for feature requests and bug reports.
Your issue may already be reported! Please search on the [issue tab](../) before creating one.

## Expected Behavior

Converting correctly 

## Current Behavior
Can't convert 1 case
 
## Context (Environment)

* **Version**: vtt_to_srt3-0.2.0.1-py3-none-any.whl 
* **Platform**: Windows 64-bit, Python 3.9-64bit
* **Subsystem**: 
* **Files**: vtt_to_srt.py

## Detailed Description

Converting this subtitle has an issue with 1 specific timestamp

VTT
```
59:53.280 --> 59:57.480 line:90% position:50% align:middle
‫text


59:57.720 --> 01:00:00.240 line:90% position:50% align:middle
‫text


01:00:00.360 --> 01:00:02.040 line:90% position:50% align:middle
text

01:00:02.160 --> 01:00:06.080 line:90% position:50% align:middle
text

01:00:06.880 --> 01:00:09.080 line:90% position:50% align:middle
text

01:00:09.200 --> 01:00:10.920 line:90% position:50% align:middle
text
```
SRT

```
664
00:59:53,280 --> 00:59:57,480
text

59:57,720 --> 01:00:00,240
text

665
01:00:00,360 --> 01:00:02,040
text

666
01:00:02,160 --> 01:00:06,080
text

667
01:00:06,880 --> 01:00:09,080
text

668
01:00:09,200 --> 01:00:10,920
text
```

Should be

```
664
00:59:53,280 --> 00:59:57,480
text

665
00:59:57,720 --> 01:00:00,240
text

666
01:00:00,360 --> 01:00:02,040
text

667
01:00:02,160 --> 01:00:06,080
text

668
01:00:06,880 --> 01:00:09,080
text

669
01:00:09,200 --> 01:00:10,920
text
```

As you notice in the minute 59:57.720 --> 01:00:00.240 it converts it to 59:57,720 --> 01:00:00,240
without the 00: and a sequence number

**Comment by jsonzilla** [comment]
@fis60 Sorry, but your input VTT has double new lines, and because that during the conversion didn't generate the counter. I think that is the problem.

**Comment by fis60** [comment]
@jsonzilla Yes i just realized this now actually and fixed it accordingly thanks
